import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { SplitText } from 'gsap/SplitText';
import ScrollMorphHero from '../components/ui/ScrollMorphHero';
import Seo from '../components/Seo';
import CtaHook from '../components/ui/CtaHook';
import { asset } from '../lib/asset';

gsap.registerPlugin(ScrollTrigger, SplitText);

// Real work lives in /public/images/portfolio projects. Files are served from the
// web root, so we just build the URL and encodeURI() the spaces in folder/file names.
// Data below names the original .jpg files; we swap to the optimized .webp siblings
// generated by scripts/optimize-images.mjs (~96% smaller).
const BASE = '/images/portfolio projects';
const src = (folder, file) => encodeURI(asset(`${BASE}/${folder}/${file.replace(/\.(jpe?g|png)$/i, '.webp')}`));

const pageImages = (folder, page, indices) =>
  indices.map((i) => src(folder, `CREATIVZEDGE PORTFOLIO_Page_${page}_Image_${String(i).padStart(4, '0')}.jpg`));

// The single hero case study that opens the story.
const featured = {
  eyebrow: 'Case Study',
  title: 'Maiyson Therys',
  desc: 'A full identity system built from the ground up — where strategy, typography and art direction converge into one unmistakable voice. This is where every CreativzEdge story begins.',
  img: src('Maiyson therys', 'CREATIVZEDGE PORTFOLIO_Page_07_Image_0001.jpg'),
};

// Each chapter is a beat in the brand-building story, in the order a brand is born.
const chapters = [
  {
    no: '01',
    label: 'Logo Design',
    headline: 'One mark, endless recognition.',
    desc: 'The single symbol that carries the weight of an entire identity. We craft marks that are simple to remember and impossible to forget.',
    images: [
      ...pageImages('Logo', '08', [4, 5, 6, 8, 11, 12, 13, 14, 15, 16, 17, 18]),
      src('Logo', 'automation.jpg'),
      src('Logo', 'hovik.jpg'),
      src('Logo', 'mulier .jpg'),
      src('Logo', 'rawyals .jpg'),
    ],
  },
  {
    no: '02',
    label: 'Brand Identity',
    headline: 'From a mark to a movement.',
    desc: 'Color, type, texture and tone — woven into a cohesive system that stays true everywhere it appears.',
    images: pageImages('Branding', '10', [1, 2, 3, 4, 5, 6, 7, 8]),
  },
  {
    no: '03',
    label: 'Social Media Design',
    headline: 'Where the brand meets its audience.',
    desc: 'Scroll-stopping creative engineered for the feed — consistent, on-brand and built to convert attention into action.',
    images: pageImages('SM-DESIGN', '09', [1, 2, 3, 4, 5, 6, 9]),
  },
  {
    no: '04',
    label: 'Packaging',
    headline: 'Design you can hold.',
    desc: 'The moment a brand becomes tangible. Packaging that earns the shelf and rewards the unboxing.',
    images: pageImages('Packaging', '12', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
    // Desktop: this chapter rides sideways while pinned (see .hscroll-* setup).
    horizontal: true,
  },
  {
    no: '05',
    label: 'Vehicle Branding',
    headline: 'Brands that move.',
    desc: 'Identity taken to the streets — turning everyday transport into bold, rolling billboards.',
    images: pageImages('Vehical Branding', '11', [1, 2, 3]),
  },
  {
    no: '06',
    label: 'Events',
    headline: 'Moments, engineered.',
    desc: 'From stage to signage, we design the spaces and details that turn an event into an experience.',
    images: [...pageImages('Events', '13', [1, 2, 3, 4, 5]), src('Events', 'CREATIVZEDGE PORTFOLIO_Page_16_Image_0001.jpg')],
  },
];

const clients = [
  src('Our Clients', 'CREATIVZEDGE PORTFOLIO_Page_16_Image_0001.jpg'),
  src('Our Clients', 'CREATIVZEDGE PORTFOLIO_Page_17_Image_0001.jpg'),
  src('Our Clients', 'CREATIVZEDGE PORTFOLIO_Page_18_Image_0001.jpg'),
];

const marqueeItems = ['Logo Design', 'Brand Identity', 'Social Media', 'Packaging', 'Vehicle Branding', 'Events'];

const Portfolio = () => {
  const rootRef = useRef(null);
  // Chapter filter — 'all' or a chapter label. Changing it re-runs the GSAP
  // setup effect below so reveals/pins rebuild against the filtered DOM.
  const [filter, setFilter] = useState('all');

  // Deep links from the services page (/portfolio#logo-design) land on their
  // chapter. Delayed so the route transition's scroll-to-top and the pinned
  // hero's ScrollTrigger setup have already settled.
  useEffect(() => {
    const hash = window.location.hash;
    if (!hash) return;
    const t = setTimeout(() => {
      const el = document.getElementById(hash.slice(1));
      if (el) {
        ScrollTrigger.refresh();
        el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }, 800);
    return () => clearTimeout(t);
  }, []);

  useEffect(() => {
    const mm = gsap.matchMedia();
    let splits = [];

    mm.add(
      {
        reduceOk: '(prefers-reduced-motion: no-preference)',
        desktop: '(min-width: 768px)',
      },
      (ctx) => {
        const { reduceOk, desktop } = ctx.conditions;
        // Reduced motion: calm, fully visible page — no scroll-bound motion at all.
        if (!reduceOk) return;

        let alive = true;

        // Start states go in first so nothing flashes before its reveal.
        gsap.set('.intro-rise, .featured-rise, .chapter-rise', { y: 36, opacity: 0 });
        // On desktop the horizontal items ride in from off-screen instead of
        // batch-revealing, so they stay visible and skip the hidden start state.
        const galleryTargets = desktop ? '.gallery-item' : '.gallery-item, .hscroll-item';
        gsap.set(galleryTargets, { y: 70, opacity: 0, scale: 0.97 });

        // Infinite marquee divider — two copies inside, so -50% loops seamlessly.
        gsap.to('.marquee-inner', { xPercent: -50, repeat: -1, duration: 28, ease: 'none' });

        // Gallery items reveal once in efficient batches as they scroll into view.
        ScrollTrigger.batch(galleryTargets, {
          start: 'top 88%',
          once: true,
          onEnter: (batch) =>
            gsap.to(batch, {
              y: 0,
              opacity: 1,
              scale: 1,
              duration: 0.9,
              ease: 'power3.out',
              stagger: 0.07,
              overwrite: true,
            }),
        });

        // Desktop: the Packaging chapter pins and travels horizontally —
        // vertical scroll drives sideways motion through the shelf of work.
        if (desktop) {
          const wrap = rootRef.current?.querySelector('.hscroll-wrap');
          const track = rootRef.current?.querySelector('.hscroll-track');
          if (wrap && track) {
            wrap.classList.add('hscroll-active');
            gsap.to(track, {
              x: () => -Math.max(track.scrollWidth - wrap.clientWidth, 0),
              ease: 'none',
              scrollTrigger: {
                trigger: wrap,
                pin: true,
                scrub: 1,
                start: 'top top',
                end: () => '+=' + Math.max(track.scrollWidth - wrap.clientWidth, 1),
                invalidateOnRefresh: true,
                anticipatePin: 0.5,
              },
            });
          }
        }

        // Text splits wait for webfonts so line breaks are measured correctly.
        (document.fonts?.ready ?? Promise.resolve()).then(() => {
          if (!alive) return;
          ctx.add(() => {
            // Intro: eyebrow → masked headline lines → paragraph, one timeline.
            const introSplit = SplitText.create('.intro-headline', { type: 'lines', mask: 'lines' });
            splits.push(introSplit);
            gsap.set(introSplit.lines, { yPercent: 110 });
            gsap
              .timeline({
                scrollTrigger: { trigger: '.portfolio-intro', start: 'top 78%', once: true },
                defaults: { ease: 'power3.out' },
              })
              .to('.intro-rise-1', { y: 0, opacity: 1, duration: 0.6 })
              .to(introSplit.lines, { yPercent: 0, duration: 1, ease: 'power4.out', stagger: 0.12 }, '-=0.25')
              .to('.intro-rise-2', { y: 0, opacity: 1, duration: 0.8 }, '-=0.55');

            // Featured case study: cover mask slides away while the artwork
            // settles from a gentle push-in, then the copy rises in step.
            gsap
              .timeline({
                scrollTrigger: { trigger: '.featured-block', start: 'top 75%', once: true },
              })
              .to('.media-cover', { yPercent: -101, duration: 1.1, ease: 'power4.out' })
              .from('.featured-img', { scale: 1.25, duration: 1.4, ease: 'power3.out' }, '<')
              .to('.featured-rise', { y: 0, opacity: 1, duration: 0.9, stagger: 0.12, ease: 'power3.out' }, '-=1');

            // Chapters: ghost number drops in, label/desc rise, headline lines
            // unmask — choreographed per chapter, playing once.
            gsap.utils.toArray('.chapter-intro').forEach((intro) => {
              const headline = intro.querySelector('.chapter-headline');
              const number = intro.querySelector('.chapter-no');
              const rises = intro.querySelectorAll('.chapter-rise');

              const split = headline ? SplitText.create(headline, { type: 'lines', mask: 'lines' }) : null;
              if (split) {
                splits.push(split);
                gsap.set(split.lines, { yPercent: 110 });
              }

              const tl = gsap.timeline({
                scrollTrigger: { trigger: intro, start: 'top 78%', once: true },
                defaults: { ease: 'power3.out' },
              });
              if (number) tl.from(number, { y: 70, opacity: 0, duration: 1, ease: 'power4.out' });
              tl.to(rises, { y: 0, opacity: 1, duration: 0.7, stagger: 0.1 }, number ? '-=0.7' : 0);
              if (split) tl.to(split.lines, { yPercent: 0, duration: 0.9, ease: 'power4.out', stagger: 0.1 }, '-=0.55');

              // Ghost number drifts slower than the page — subtle scrubbed depth.
              if (number) {
                gsap.fromTo(
                  number,
                  { yPercent: 14 },
                  {
                    yPercent: -14,
                    ease: 'none',
                    scrollTrigger: { trigger: intro, start: 'top bottom', end: 'bottom top', scrub: true },
                  }
                );
              }
            });

            // Triggers are created in two waves (sync + after fonts), so make
            // sure refresh order matches page order before measuring.
            ScrollTrigger.sort();
            ScrollTrigger.refresh();
          });
        });

        return () => {
          alive = false;
          rootRef.current?.querySelector('.hscroll-wrap')?.classList.remove('hscroll-active');
          splits.forEach((s) => s.revert());
          splits = [];
        };
      },
      rootRef
    );

    // The masonry columns grow as each lazy image loads, which shifts every
    // trigger below it. Re-measure (debounced) so reveals always fire exactly
    // where they should instead of early/late on a stale layout.
    let refreshCall;
    const queueRefresh = () => {
      refreshCall?.kill();
      refreshCall = gsap.delayedCall(0.2, () => ScrollTrigger.refresh());
    };
    const pendingImgs = Array.from(rootRef.current?.querySelectorAll('img') ?? []).filter((img) => !img.complete);
    pendingImgs.forEach((img) => img.addEventListener('load', queueRefresh, { once: true }));

    return () => {
      refreshCall?.kill();
      pendingImgs.forEach((img) => img.removeEventListener('load', queueRefresh));
      mm.revert();
    };
  }, [filter]);

  return (
    // overflow-clip (not hidden!) — clips the ambient glows that stick out past
    // the page edges without creating a scroll container, so position:sticky
    // (hero) and pinning (packaging chapter) keep working.
    <div ref={rootRef} className="relative pb-20 overflow-clip min-h-screen bg-background">
      <Seo
        title="Portfolio — Logo, Branding & Packaging Design Work | CreativzEdge"
        description="Real work for real brands: logo design, brand identity systems, packaging, social media creatives, vehicle branding and event design crafted by CreativzEdge in Chennai & Mumbai."
        path="/portfolio"
        breadcrumb="Portfolio"
      />
      {/* Immersive scroll-morph hero — scatter → line → circle → arc, pinned and
          driven by native scroll (it renders its own tall scroll section) */}
      <ScrollMorphHero />

      <div className="ambient-glow top-[40%] left-[-10%] bg-primary/20"></div>
      <div className="ambient-glow bottom-[-10%] right-[-10%] bg-secondary/10"></div>

      <section className="max-w-7xl mx-auto px-margin relative z-10 pt-32">
        {/* Intro */}
        <div className="portfolio-intro text-center mb-28">
          <div className="intro-rise intro-rise-1 flex items-center justify-center gap-3 mb-8">
            <div className="w-8 h-[1px] bg-secondary/40"></div>
            <span className="font-outfit text-[12px] font-black tracking-[0.4em] text-secondary uppercase">The Work</span>
            <div className="w-8 h-[1px] bg-secondary/40"></div>
          </div>
          <h1 className="intro-headline syne-title text-[clamp(2rem,7vw,5.5rem)] text-primary mb-10 leading-[1.1]">
            A Brand, <span className="text-gradient">Built.</span>
          </h1>
          <p className="intro-rise intro-rise-2 font-inter text-body-lg text-on-surface-variant max-w-3xl mx-auto leading-relaxed">
            Six chapters, one journey — follow how CreativzEdge takes an idea from a single sketch to a living,
            breathing identity out in the world.
          </p>
        </div>

        {/* Featured case study */}
        <div className="featured-block grid lg:grid-cols-2 gap-12 items-center mb-40">
          <div className="featured-media relative rounded-3xl overflow-hidden glass-card !p-0 bg-white/[0.02]">
            <img
              src={featured.img}
              alt={featured.title}
              className="featured-img block w-full h-auto object-contain"
            />
            {/* Cover panel that unmasks the artwork on scroll */}
            <div className="media-cover absolute inset-0 bg-background z-10 pointer-events-none"></div>
          </div>
          <div className="lg:pl-6">
            <span className="featured-rise font-outfit text-[11px] font-black tracking-[0.3em] text-accent uppercase block mb-5">
              {featured.eyebrow}
            </span>
            <h2 className="featured-rise font-syne text-4xl md:text-5xl text-primary uppercase leading-[0.95] mb-8">
              {featured.title}
            </h2>
            <p className="featured-rise font-inter text-on-surface-variant leading-relaxed text-lg">{featured.desc}</p>
            <div className="featured-rise w-16 h-[2px] bg-accent mt-10"></div>
          </div>
        </div>

        {/* Chapter filter — one pill per category */}
        <div className="mb-20 flex flex-wrap justify-center gap-3">
          {['All', ...chapters.map((c) => c.label)].map((label) => {
            const value = label === 'All' ? 'all' : label;
            const isActive = filter === value;
            return (
              <button
                key={label}
                type="button"
                onClick={() => setFilter(value)}
                aria-pressed={isActive}
                className={`px-5 py-2.5 rounded-full font-outfit text-[11px] font-black uppercase tracking-widest border transition-all ${
                  isActive
                    ? 'bg-primary text-surface border-primary'
                    : 'glass text-secondary border-primary/10 hover:border-accent hover:text-primary'
                }`}
              >
                {label}
              </button>
            );
          })}
        </div>

        {/* Story chapters — ids let service cards deep-link straight to their work */}
        {chapters.filter((c) => filter === 'all' || c.label === filter).map((chapter, ci) => (
          <div key={chapter.no} id={chapter.label.toLowerCase().replace(/\s+/g, '-')} className="mb-40 scroll-mt-32">
            <div className={`chapter-intro flex flex-col md:flex-row md:items-end gap-6 mb-14 ${ci % 2 === 1 ? 'md:flex-row-reverse md:text-right' : ''}`}>
              <span className="chapter-no font-syne text-[5rem] md:text-[8rem] leading-none text-primary/5 font-extrabold select-none">
                {chapter.no}
              </span>
              <div className={ci % 2 === 1 ? 'md:ml-auto' : ''}>
                <span className="chapter-rise font-outfit text-[11px] font-black tracking-[0.3em] text-accent uppercase block mb-4">
                  {chapter.label}
                </span>
                <h2 className="chapter-headline font-syne text-3xl md:text-4xl text-primary uppercase leading-tight mb-4 max-w-xl">
                  {chapter.headline}
                </h2>
                <p className={`chapter-rise font-inter text-on-surface-variant leading-relaxed max-w-xl ${ci % 2 === 1 ? 'md:ml-auto' : ''}`}>
                  {chapter.desc}
                </p>
              </div>
            </div>

            {chapter.horizontal ? (
              /* Desktop: pinned horizontal ride (activated via .hscroll-active).
                 Mobile / reduced motion: a plain responsive grid. */
              <div className="hscroll-wrap">
                <div className="hscroll-track grid grid-cols-1 sm:grid-cols-2 gap-6">
                  {chapter.images.map((img, i) => (
                    <div
                      key={i}
                      className="hscroll-item group relative rounded-2xl overflow-hidden glass-card !p-0"
                    >
                      <img
                        src={img}
                        alt={`${chapter.label} work ${i + 1}`}
                        loading="lazy"
                        decoding="async"
                        className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-[1.06]"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                      <span className="absolute bottom-4 left-5 font-outfit text-[10px] font-black tracking-widest text-white uppercase opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-500">
                        {chapter.label}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              /* Masonry gallery */
              <div className="columns-1 sm:columns-2 lg:columns-3 gap-6 [column-fill:_balance]">
                {chapter.images.map((img, i) => (
                  <div
                    key={i}
                    className="gallery-item group relative mb-6 break-inside-avoid rounded-2xl overflow-hidden glass-card !p-0"
                  >
                    <img
                      src={img}
                      alt={`${chapter.label} work ${i + 1}`}
                      loading="lazy"
                      decoding="async"
                      className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-[1.06]"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                    <span className="absolute bottom-4 left-5 font-outfit text-[10px] font-black tracking-widest text-white uppercase opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-500">
                      {chapter.label}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}
      </section>

      {/* Marquee divider — full-bleed strip of everything the studio crafts */}
      <div
        aria-hidden="true"
        className="marquee relative w-screen left-1/2 -translate-x-1/2 overflow-hidden py-7 border-y border-primary/10 mb-32 select-none"
      >
        <div className="marquee-inner flex whitespace-nowrap will-change-transform">
          {[0, 1].map((dup) => (
            <div key={dup} className="flex shrink-0 items-center">
              {marqueeItems.map((item) => (
                <span key={item} className="flex items-center font-syne text-2xl md:text-4xl uppercase text-primary/10 font-extrabold">
                  <span className="mx-6">{item}</span>
                  <span className="text-accent/40 text-lg md:text-2xl">✦</span>
                </span>
              ))}
            </div>
          ))}
        </div>
      </div>

      <section className="max-w-7xl mx-auto px-margin relative z-10">
        {/* Closing — trusted by */}
        <div className="chapter-intro text-center mb-16">
          <span className="chapter-rise font-outfit text-[11px] font-black tracking-[0.3em] text-accent uppercase block mb-5">
            The Result
          </span>
          <h2 className="chapter-headline font-syne text-3xl md:text-5xl text-primary uppercase leading-tight mb-6">
            The Company <span className="text-gradient">We Keep.</span>
          </h2>
          <p className="chapter-rise font-inter text-on-surface-variant max-w-2xl mx-auto leading-relaxed">
            The work speaks for itself — and so do the partners who trust us to tell their story.
          </p>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {clients.map((img, i) => (
            <div key={i} className="gallery-item rounded-2xl overflow-hidden glass-card !p-0">
              <img src={img} alt={`Client ${i + 1}`} loading="lazy" decoding="async" className="w-full h-auto object-cover" />
            </div>
          ))}
        </div>
      </section>

      {/* Engagement hook */}
      <CtaHook
        variant="circle"
        eyebrow="You've Seen the Work"
        title={
          <>
            Like what you see? Your brand could be <span className="text-gradient">next.</span>
          </>
        }
        subtitle="Every project here started with a single conversation. Let's start yours."
        primary={{ label: 'Start a Project', to: '/contact' }}
        secondary={{ label: 'Our Services', to: '/services' }}
      />
    </div>
  );
};

export default Portfolio;
